--------------------------------------------------------
--  DDL for Index ORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."ORDERS_PK" ON "BOM"."ORDERS" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COUPON_CDATE_INDEX
--------------------------------------------------------

  CREATE INDEX "BOM"."COUPON_CDATE_INDEX" ON "BOM"."COUPON" ("CDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."OITEM_PK" ON "BOM"."OITEM" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SCHEDULE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."SCHEDULE_PK" ON "BOM"."SCHEDULE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CART_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."CART_PK" ON "BOM"."CART" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BANNER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."BANNER_PK" ON "BOM"."BANNER" ("CATEGORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BRANCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."BRANCH_PK" ON "BOM"."BRANCH" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REVIEW_INDEX_2
--------------------------------------------------------

  CREATE INDEX "BOM"."REVIEW_INDEX_2" ON "BOM"."REVIEW" ("LIKE_COUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REVIEW_INDEX_1
--------------------------------------------------------

  CREATE INDEX "BOM"."REVIEW_INDEX_1" ON "BOM"."REVIEW" ("REG_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OCLASS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."OCLASS_PK" ON "BOM"."OCLASS" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REVIEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."REVIEW_PK" ON "BOM"."REVIEW" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OSUBS_INDEX_1
--------------------------------------------------------

  CREATE INDEX "BOM"."OSUBS_INDEX_1" ON "BOM"."OSUBS" ("DELIVERY_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ECOMMENT_INDEX_1
--------------------------------------------------------

  CREATE INDEX "BOM"."ECOMMENT_INDEX_1" ON "BOM"."ECOMMENT" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COUPON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."COUPON_PK" ON "BOM"."COUPON" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."PRODUCT_PK" ON "BOM"."PRODUCT" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ECOMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."ECOMMENT_PK" ON "BOM"."ECOMMENT" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_INDEX_3
--------------------------------------------------------

  CREATE INDEX "BOM"."MEMBER_INDEX_3" ON "BOM"."MEMBER" ("GRADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DELIVERY_INFO_INDEX_1
--------------------------------------------------------

  CREATE INDEX "BOM"."DELIVERY_INFO_INDEX_1" ON "BOM"."DELIVERY_INFO" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MYQ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."MYQ_PK" ON "BOM"."MYQ" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DELIVERY_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."DELIVERY_INFO_PK" ON "BOM"."DELIVERY_INFO" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDERS_STATUS_INDEX
--------------------------------------------------------

  CREATE INDEX "BOM"."ORDERS_STATUS_INDEX" ON "BOM"."ORDERS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OSUBS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."OSUBS_PK" ON "BOM"."OSUBS" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ECOMMENT_INDEX_2
--------------------------------------------------------

  CREATE INDEX "BOM"."ECOMMENT_INDEX_2" ON "BOM"."ECOMMENT" ("EVENT_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."SUBS_PK" ON "BOM"."SUBS" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OCLASS_INDEX_2
--------------------------------------------------------

  CREATE INDEX "BOM"."OCLASS_INDEX_2" ON "BOM"."OCLASS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UC_COLOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."UC_COLOR" ON "BOM"."BRANCH" ("COLOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FLOWER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."FLOWER_PK" ON "BOM"."FLOWER" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SCHEDULE_INDEX_1
--------------------------------------------------------

  CREATE INDEX "BOM"."SCHEDULE_INDEX_1" ON "BOM"."SCHEDULE" ("SMONTH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."EVENT_PK" ON "BOM"."EVENT" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OCLASS_INDEX_1
--------------------------------------------------------

  CREATE INDEX "BOM"."OCLASS_INDEX_1" ON "BOM"."OCLASS" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OCLASS_INDEX_3
--------------------------------------------------------

  CREATE INDEX "BOM"."OCLASS_INDEX_3" ON "BOM"."OCLASS" ("REVIEW_CHECK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OITEM_INDEX_1
--------------------------------------------------------

  CREATE INDEX "BOM"."OITEM_INDEX_1" ON "BOM"."OITEM" ("ORDERS_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FCLASS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."FCLASS_PK" ON "BOM"."FCLASS" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDERS_INDEX_1
--------------------------------------------------------

  CREATE INDEX "BOM"."ORDERS_INDEX_1" ON "BOM"."ORDERS" ("ODATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDERS_INDEX_2
--------------------------------------------------------

  CREATE INDEX "BOM"."ORDERS_INDEX_2" ON "BOM"."ORDERS" ("PAY_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_INDEX_2
--------------------------------------------------------

  CREATE INDEX "BOM"."MEMBER_INDEX_2" ON "BOM"."MEMBER" ("GENDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FAQ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."FAQ_PK" ON "BOM"."FAQ" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CART_INDEX_1
--------------------------------------------------------

  CREATE INDEX "BOM"."CART_INDEX_1" ON "BOM"."CART" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_INDEX_4
--------------------------------------------------------

  CREATE INDEX "BOM"."MEMBER_INDEX_4" ON "BOM"."MEMBER" ("QUIT_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UC_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."UC_NAME" ON "BOM"."BRANCH" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."MEMBER_PK" ON "BOM"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CHOICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOM"."CHOICE_PK" ON "BOM"."CHOICE" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDERS_INDEX_3
--------------------------------------------------------

  CREATE INDEX "BOM"."ORDERS_INDEX_3" ON "BOM"."ORDERS" ("PAY_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_INDEX_1
--------------------------------------------------------

  CREATE INDEX "BOM"."MEMBER_INDEX_1" ON "BOM"."MEMBER" ("BIRTH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger BRANCH_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."BRANCH_AI_TRG" 
BEFORE INSERT ON BOM.BRANCH 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT BRANCH_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."BRANCH_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CART_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."CART_AI_TRG" 
BEFORE INSERT ON BOM.CART 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT CART_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."CART_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CHOICE_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."CHOICE_AI_TRG" 
BEFORE INSERT ON BOM.CHOICE
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT CHOICE_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."CHOICE_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COUPON_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."COUPON_AI_TRG" 
BEFORE INSERT ON BOM.COUPON 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT COUPON_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."COUPON_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DELIVERY_INFO_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."DELIVERY_INFO_AI_TRG" 
BEFORE INSERT ON BOM.DELIVERY_INFO 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT DELIVERY_INFO_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."DELIVERY_INFO_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ECOMMENT_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."ECOMMENT_AI_TRG" 
BEFORE INSERT ON BOM.ECOMMENT 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT ECOMMENT_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."ECOMMENT_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EVENT_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."EVENT_AI_TRG" 
BEFORE INSERT ON BOM.EVENT 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT EVENT_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."EVENT_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FAQ_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."FAQ_AI_TRG" 
BEFORE INSERT ON BOM.FAQ 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT FAQ_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."FAQ_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FCLASS_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."FCLASS_AI_TRG" 
BEFORE INSERT ON BOM.FCLASS 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT FCLASS_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."FCLASS_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FLOWER_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."FLOWER_AI_TRG" 
BEFORE INSERT ON BOM.FLOWER 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT FLOWER_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."FLOWER_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MYQ_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."MYQ_AI_TRG" 
BEFORE INSERT ON BOM.MYQ 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT MYQ_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."MYQ_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OCLASS_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."OCLASS_AI_TRG" 
BEFORE INSERT ON BOM.OCLASS 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT OCLASS_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."OCLASS_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OITEM_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."OITEM_AI_TRG" 
BEFORE INSERT ON BOM.OITEM 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT OITEM_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."OITEM_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDERS_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."ORDERS_AI_TRG" 
BEFORE INSERT ON BOM.ORDERS 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT ORDERS_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."ORDERS_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OSUBS_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."OSUBS_AI_TRG" 
BEFORE INSERT ON BOM.OSUBS 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT OSUBS_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."OSUBS_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCT_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."PRODUCT_AI_TRG" 
BEFORE INSERT ON BOM.PRODUCT 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT PRODUCT_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."PRODUCT_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REVIEW_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."REVIEW_AI_TRG" 
BEFORE INSERT ON BOM.REVIEW 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT REVIEW_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."REVIEW_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REVIEW_LIKE_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."REVIEW_LIKE_AI_TRG" 
before INSERT ON BOM.REVIEW_LIKE
for each row
begin
  select REVIEW_LIKE_SEQ.nextval into :new.idx from dual;
end;
/
ALTER TRIGGER "BOM"."REVIEW_LIKE_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SCHEDULE_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."SCHEDULE_AI_TRG" 
BEFORE INSERT ON BOM.SCHEDULE 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT SCHEDULE_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."SCHEDULE_AI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SUBS_AI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOM"."SUBS_AI_TRG" 
BEFORE INSERT ON BOM.SUBS 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT SUBS_SEQ.NEXTVAL
    INTO :NEW.IDX
    FROM DUAL;
END;


/
ALTER TRIGGER "BOM"."SUBS_AI_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table OSUBS
--------------------------------------------------------

  ALTER TABLE "BOM"."OSUBS" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OSUBS" MODIFY ("OITEM_IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OSUBS" MODIFY ("MONTH" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OSUBS" MODIFY ("DELIVERY_DATE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OSUBS" ADD CONSTRAINT "OSUBS_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "BOM"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BOM"."MEMBER" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "BOM"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."MEMBER" MODIFY ("BIRTH" NOT NULL ENABLE);
  ALTER TABLE "BOM"."MEMBER" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "BOM"."MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."MEMBER" MODIFY ("GRADE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."MEMBER" MODIFY ("POINT" NOT NULL ENABLE);
  ALTER TABLE "BOM"."MEMBER" MODIFY ("QUIT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "BOM"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW_LIKE
--------------------------------------------------------

  ALTER TABLE "BOM"."REVIEW_LIKE" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BANNER
--------------------------------------------------------

  ALTER TABLE "BOM"."BANNER" ADD CONSTRAINT "BANNER_PK" PRIMARY KEY ("CATEGORY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOM"."BANNER" MODIFY ("CATEGORY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OITEM
--------------------------------------------------------

  ALTER TABLE "BOM"."OITEM" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OITEM" MODIFY ("ORDERS_IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OITEM" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OITEM" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OITEM" MODIFY ("IMAGE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OITEM" MODIFY ("REVIEW_CHECK" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OITEM" ADD CONSTRAINT "OITEM_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FAQ
--------------------------------------------------------

  ALTER TABLE "BOM"."FAQ" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FAQ" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FAQ" MODIFY ("QUESTION" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FAQ" ADD CONSTRAINT "FAQ_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "BOM"."CART" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."CART" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOM"."CART" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "BOM"."CART" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "BOM"."CART" ADD CONSTRAINT "CART_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOM"."CART" MODIFY ("LETTER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OCLASS
--------------------------------------------------------

  ALTER TABLE "BOM"."OCLASS" MODIFY ("DISCOUNT_TOTAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("REG_COUNT" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("PAY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("PAY_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("DISCOUNT_GRADE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("DISCOUNT_POINT" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("FCLASS_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("BRANCH_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("BRANCH_ADDR" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("FCLASS_IMAGE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("SCHEDULE_DATE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("SCHEDULE_START_TIME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("SCHEDULE_END_TIME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("FCLASS_COUNT" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" MODIFY ("REVIEW_CHECK" NOT NULL ENABLE);
  ALTER TABLE "BOM"."OCLASS" ADD CONSTRAINT "OCLASS_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SCHEDULE
--------------------------------------------------------

  ALTER TABLE "BOM"."SCHEDULE" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SCHEDULE" MODIFY ("BRANCH_IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SCHEDULE" MODIFY ("FCLASS_IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SCHEDULE" MODIFY ("SDATE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SCHEDULE" MODIFY ("SMONTH" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SCHEDULE" MODIFY ("SDAY" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SCHEDULE" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SCHEDULE" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SCHEDULE" MODIFY ("TOTAL_COUNT" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SCHEDULE" MODIFY ("REG_COUNT" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SCHEDULE" ADD CONSTRAINT "SCHEDULE_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "BOM"."PRODUCT" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."PRODUCT" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "BOM"."PRODUCT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."PRODUCT" MODIFY ("SUBHEADER" NOT NULL ENABLE);
  ALTER TABLE "BOM"."PRODUCT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."PRODUCT" MODIFY ("IMAGE1" NOT NULL ENABLE);
  ALTER TABLE "BOM"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "BOM"."REVIEW" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."REVIEW" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "BOM"."REVIEW" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."REVIEW" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOM"."REVIEW" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."REVIEW" MODIFY ("STAR" NOT NULL ENABLE);
  ALTER TABLE "BOM"."REVIEW" MODIFY ("LIKE_COUNT" NOT NULL ENABLE);
  ALTER TABLE "BOM"."REVIEW" ADD CONSTRAINT "REVIEW_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MYQ
--------------------------------------------------------

  ALTER TABLE "BOM"."MYQ" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."MYQ" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."MYQ" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOM"."MYQ" MODIFY ("EMAIL_SEND" NOT NULL ENABLE);
  ALTER TABLE "BOM"."MYQ" ADD CONSTRAINT "MYQ_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FCLASS
--------------------------------------------------------

  ALTER TABLE "BOM"."FCLASS" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FCLASS" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FCLASS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FCLASS" MODIFY ("SUBHEADER" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FCLASS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FCLASS" MODIFY ("IMAGE1" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FCLASS" MODIFY ("COUNT" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FCLASS" ADD CONSTRAINT "FCLASS_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BRANCH
--------------------------------------------------------

  ALTER TABLE "BOM"."BRANCH" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."BRANCH" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."BRANCH" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "BOM"."BRANCH" MODIFY ("ADDR" NOT NULL ENABLE);
  ALTER TABLE "BOM"."BRANCH" MODIFY ("MAP_IMAGE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."BRANCH" ADD CONSTRAINT "BRANCH_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOM"."BRANCH" ADD CONSTRAINT "UC_NAME" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FLOWER
--------------------------------------------------------

  ALTER TABLE "BOM"."FLOWER" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FLOWER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FLOWER" MODIFY ("SUBHEADER" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FLOWER" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FLOWER" MODIFY ("FSIZE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FLOWER" MODIFY ("IMAGE1" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FLOWER" MODIFY ("FREE_DELIVERY" NOT NULL ENABLE);
  ALTER TABLE "BOM"."FLOWER" ADD CONSTRAINT "FLOWER_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ECOMMENT
--------------------------------------------------------

  ALTER TABLE "BOM"."ECOMMENT" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ECOMMENT" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ECOMMENT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ECOMMENT" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ECOMMENT" MODIFY ("REPORT" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ECOMMENT" MODIFY ("EVENT_IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ECOMMENT" ADD CONSTRAINT "ECOMMENT_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHOICE
--------------------------------------------------------

  ALTER TABLE "BOM"."CHOICE" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."CHOICE" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "BOM"."CHOICE" MODIFY ("PRODUCT_IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."CHOICE" MODIFY ("CART_IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."CHOICE" ADD CONSTRAINT "CHOICE_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COUPON
--------------------------------------------------------

  ALTER TABLE "BOM"."COUPON" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."COUPON" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."COUPON" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOM"."COUPON" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BOM"."COUPON" MODIFY ("POINT" NOT NULL ENABLE);
  ALTER TABLE "BOM"."COUPON" MODIFY ("CDATE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."COUPON" ADD CONSTRAINT "COUPON_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "BOM"."ORDERS" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ORDERS" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ORDERS" MODIFY ("ODATE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ORDERS" MODIFY ("RECEIVER_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ORDERS" MODIFY ("RECEIVER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ORDERS" MODIFY ("RECEIVER_ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ORDERS" MODIFY ("RECEIVER_ADDR_BASE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ORDERS" MODIFY ("PAY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ORDERS" MODIFY ("PAY_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ORDERS" MODIFY ("PAY_DELIVERY" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ORDERS" MODIFY ("DISCOUNT_GRADE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ORDERS" MODIFY ("DISCOUNT_POINT" NOT NULL ENABLE);
  ALTER TABLE "BOM"."ORDERS" ADD CONSTRAINT "ORDERS_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DELIVERY_INFO
--------------------------------------------------------

  ALTER TABLE "BOM"."DELIVERY_INFO" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."DELIVERY_INFO" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOM"."DELIVERY_INFO" MODIFY ("RECEIVER_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."DELIVERY_INFO" MODIFY ("RECEIVER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."DELIVERY_INFO" MODIFY ("RECEIVER_ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."DELIVERY_INFO" MODIFY ("RECEIVER_ADDR_BASE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."DELIVERY_INFO" ADD CONSTRAINT "DELIVERY_INFO_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE "BOM"."EVENT" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."EVENT" MODIFY ("THUMB" NOT NULL ENABLE);
  ALTER TABLE "BOM"."EVENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."EVENT" MODIFY ("IMAGE1" NOT NULL ENABLE);
  ALTER TABLE "BOM"."EVENT" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."EVENT" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."EVENT" ADD CONSTRAINT "EVENT_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBS
--------------------------------------------------------

  ALTER TABLE "BOM"."SUBS" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SUBS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SUBS" MODIFY ("SUBHEADER" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SUBS" MODIFY ("SUMMARY" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SUBS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SUBS" MODIFY ("IMAGE1" NOT NULL ENABLE);
  ALTER TABLE "BOM"."SUBS" ADD CONSTRAINT "SUBS_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "BOM"."CART" ADD CONSTRAINT "FK_CART_FLOWER_IDX_FLOWER_IDX" FOREIGN KEY ("FLOWER_IDX")
	  REFERENCES "BOM"."FLOWER" ("IDX") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BOM"."CART" ADD CONSTRAINT "FK_CART_MEMBER_ID_MEMBER_ID" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "BOM"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BOM"."CART" ADD CONSTRAINT "FK_CART_PRODUCT_IDX_PRODUCT_ID" FOREIGN KEY ("PRODUCT_IDX")
	  REFERENCES "BOM"."PRODUCT" ("IDX") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BOM"."CART" ADD CONSTRAINT "FK_CART_SUBS_IDX_SUBS_IDX" FOREIGN KEY ("SUBS_IDX")
	  REFERENCES "BOM"."SUBS" ("IDX") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHOICE
--------------------------------------------------------

  ALTER TABLE "BOM"."CHOICE" ADD CONSTRAINT "FK_CHOICE_CART_IDX_CART_IDX" FOREIGN KEY ("CART_IDX")
	  REFERENCES "BOM"."CART" ("IDX") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BOM"."CHOICE" ADD CONSTRAINT "FK_CHOICE_PRODUCT_IDX_PRODUCT_" FOREIGN KEY ("PRODUCT_IDX")
	  REFERENCES "BOM"."PRODUCT" ("IDX") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COUPON
--------------------------------------------------------

  ALTER TABLE "BOM"."COUPON" ADD CONSTRAINT "FK_COUPON_MEMBER_ID_MEMBER_ID" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "BOM"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DELIVERY_INFO
--------------------------------------------------------

  ALTER TABLE "BOM"."DELIVERY_INFO" ADD CONSTRAINT "FK_DELIVERY_INFO_MEMBER_ID_MEM" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "BOM"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ECOMMENT
--------------------------------------------------------

  ALTER TABLE "BOM"."ECOMMENT" ADD CONSTRAINT "FK_ECOMMENT_EVENT_IDX_EVENT_ID" FOREIGN KEY ("EVENT_IDX")
	  REFERENCES "BOM"."EVENT" ("IDX") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BOM"."ECOMMENT" ADD CONSTRAINT "FK_ECOMMENT_MEMBER_ID_MEMBER_I" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "BOM"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FCB
--------------------------------------------------------

  ALTER TABLE "BOM"."FCB" ADD CONSTRAINT "FCB_BRANCH_FK" FOREIGN KEY ("BRANCH_IDX")
	  REFERENCES "BOM"."BRANCH" ("IDX") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BOM"."FCB" ADD CONSTRAINT "FCB_FCLASS_FK" FOREIGN KEY ("FCLASS_IDX")
	  REFERENCES "BOM"."FCLASS" ("IDX") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAIN
--------------------------------------------------------

  ALTER TABLE "BOM"."MAIN" ADD CONSTRAINT "MAIN_FCLASS_IDX_BIG_FK" FOREIGN KEY ("FCLASS_IDX_BIG")
	  REFERENCES "BOM"."FCLASS" ("IDX") ENABLE;
  ALTER TABLE "BOM"."MAIN" ADD CONSTRAINT "MAIN_FCLASS_IDX_SMALL_FK" FOREIGN KEY ("FCLASS_IDX_SMALL")
	  REFERENCES "BOM"."FCLASS" ("IDX") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MYQ
--------------------------------------------------------

  ALTER TABLE "BOM"."MYQ" ADD CONSTRAINT "FK_MYQ_MEMBER_ID_MEMBER_ID" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "BOM"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OCLASS
--------------------------------------------------------

  ALTER TABLE "BOM"."OCLASS" ADD CONSTRAINT "FK_OCLASS_MEMBER_ID_MEMBER_ID" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "BOM"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BOM"."OCLASS" ADD CONSTRAINT "OCLASS_FK1" FOREIGN KEY ("SCHEDULE_IDX")
	  REFERENCES "BOM"."SCHEDULE" ("IDX") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OITEM
--------------------------------------------------------

  ALTER TABLE "BOM"."OITEM" ADD CONSTRAINT "FK_OITEM_ORDERS_IDX_ORDERS_IDX" FOREIGN KEY ("ORDERS_IDX")
	  REFERENCES "BOM"."ORDERS" ("IDX") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "BOM"."ORDERS" ADD CONSTRAINT "FK_ORDERS_MEMBER_ID_MEMBER_ID" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "BOM"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OSUBS
--------------------------------------------------------

  ALTER TABLE "BOM"."OSUBS" ADD CONSTRAINT "FK_OSUBS_OITEM_IDX_OITEM_IDX" FOREIGN KEY ("OITEM_IDX")
	  REFERENCES "BOM"."OITEM" ("IDX") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "BOM"."REVIEW" ADD CONSTRAINT "FK_REVIEW_MEMBER_ID_MEMBER_ID" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "BOM"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW_LIKE
--------------------------------------------------------

  ALTER TABLE "BOM"."REVIEW_LIKE" ADD CONSTRAINT "REVIEW_LIKE_MEMBER_FK" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "BOM"."MEMBER" ("ID") ENABLE;
  ALTER TABLE "BOM"."REVIEW_LIKE" ADD CONSTRAINT "REVIEW_LIKE_REVIEW_FK" FOREIGN KEY ("REVIEW_IDX")
	  REFERENCES "BOM"."REVIEW" ("IDX") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCHEDULE
--------------------------------------------------------

  ALTER TABLE "BOM"."SCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_BRANCH_IDX_BRANCH_" FOREIGN KEY ("BRANCH_IDX")
	  REFERENCES "BOM"."BRANCH" ("IDX") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BOM"."SCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_FCLASS_IDX_FCLASS_" FOREIGN KEY ("FCLASS_IDX")
	  REFERENCES "BOM"."FCLASS" ("IDX") ON DELETE CASCADE ENABLE;
