-- 민호 추가 create user --
-- 기존 유저가 있으면 삭제하고 재생성하는 로직입니다 --
drop user bom cascade;
create user bom identified by bompw
default tablespace users
temporary tablespace temp;

grant resource, connect to bom;



--------------------------------------------------------
--  파일이 생성됨 - 화요일-4월-13-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BRANCH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."BRANCH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CART_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."CART_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 381 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CHOICE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."CHOICE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 301 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COUPON_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."COUPON_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DELIVERY_INFO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."DELIVERY_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ECOMMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."ECOMMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EVENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."EVENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FAQ_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."FAQ_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FCLASS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."FCLASS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FLOWER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."FLOWER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MYQ_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."MYQ_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OCLASS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."OCLASS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 321 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."OITEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 281 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORDERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."ORDERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 261 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OSUBS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."OSUBS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODUCT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."PRODUCT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REVIEW_LIKE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."REVIEW_LIKE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 266 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REVIEW_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."REVIEW_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 381 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SCHEDULE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."SCHEDULE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 281 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SUBS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOM"."SUBS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BANNER
--------------------------------------------------------

  CREATE TABLE "BOM"."BANNER" 
   (	"CATEGORY" VARCHAR2(50 BYTE), 
	"IMAGE" VARCHAR2(200 BYTE), 
	"TITLE" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BOM"."BANNER"."CATEGORY" IS 'subs, flower, product, fclass';
   COMMENT ON COLUMN "BOM"."BANNER"."IMAGE" IS '이미지 주소';
   COMMENT ON COLUMN "BOM"."BANNER"."TITLE" IS '배너 타이틀';
   COMMENT ON COLUMN "BOM"."BANNER"."CONTENT" IS '배너 설명글';
--------------------------------------------------------
--  DDL for Table BRANCH
--------------------------------------------------------

  CREATE TABLE "BOM"."BRANCH" 
   (	"IDX" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"COLOR" VARCHAR2(10 BYTE), 
	"ADDR" VARCHAR2(500 BYTE), 
	"MAP_IMAGE" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BOM"."BRANCH"."IDX" IS '지점 인덱스';
   COMMENT ON COLUMN "BOM"."BRANCH"."NAME" IS '지점명';
   COMMENT ON COLUMN "BOM"."BRANCH"."COLOR" IS '지점 색깔';
   COMMENT ON COLUMN "BOM"."BRANCH"."ADDR" IS '지점 주소';
   COMMENT ON COLUMN "BOM"."BRANCH"."MAP_IMAGE" IS '지도 이미지';
   COMMENT ON TABLE "BOM"."BRANCH"  IS '지점';
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "BOM"."CART" 
   (	"IDX" NUMBER, 
	"MEMBER_ID" VARCHAR2(50 BYTE), 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"SUBS_IDX" NUMBER, 
	"FLOWER_IDX" NUMBER, 
	"PRODUCT_IDX" NUMBER, 
	"QUANTITY" NUMBER, 
	"SUBS_MONTH" NUMBER, 
	"SUBS_START_DATE" DATE, 
	"LETTER" NUMBER DEFAULT 0, 
	"REQUEST_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BOM"."CART"."IDX" IS '카트 인덱스';
   COMMENT ON COLUMN "BOM"."CART"."MEMBER_ID" IS '주문자 아이디';
   COMMENT ON COLUMN "BOM"."CART"."CATEGORY" IS '꽃다발, 정기구독, 소품샵, 플라워클래스';
   COMMENT ON COLUMN "BOM"."CART"."SUBS_IDX" IS '정기구독 인덱스';
   COMMENT ON COLUMN "BOM"."CART"."FLOWER_IDX" IS '꽃다발 인덱스';
   COMMENT ON COLUMN "BOM"."CART"."PRODUCT_IDX" IS '소품샵 인덱스';
   COMMENT ON COLUMN "BOM"."CART"."QUANTITY" IS '상품 수량';
   COMMENT ON COLUMN "BOM"."CART"."SUBS_MONTH" IS '구독 기간';
   COMMENT ON COLUMN "BOM"."CART"."SUBS_START_DATE" IS '구독 시작 날짜';
   COMMENT ON COLUMN "BOM"."CART"."LETTER" IS '1이면 편지 추가';
   COMMENT ON COLUMN "BOM"."CART"."REQUEST_DATE" IS '수령 요청일';
   COMMENT ON TABLE "BOM"."CART"  IS '장바구니';
--------------------------------------------------------
--  DDL for Table CHOICE
--------------------------------------------------------

  CREATE TABLE "BOM"."CHOICE" 
   (	"IDX" NUMBER, 
	"PRODUCT_IDX" NUMBER, 
	"CART_IDX" NUMBER, 
	"QUANTITY" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BOM"."CHOICE"."IDX" IS '추가상품 인덱스';
   COMMENT ON COLUMN "BOM"."CHOICE"."PRODUCT_IDX" IS '소품샵 인덱스';
   COMMENT ON COLUMN "BOM"."CHOICE"."CART_IDX" IS '장바구니 인덱스';
   COMMENT ON COLUMN "BOM"."CHOICE"."QUANTITY" IS '수량';
   COMMENT ON TABLE "BOM"."CHOICE"  IS '추가 상품 테이블';
--------------------------------------------------------
--  DDL for Table COUPON
--------------------------------------------------------

  CREATE TABLE "BOM"."COUPON" 
   (	"IDX" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"MEMBER_ID" VARCHAR2(50 BYTE), 
	"STATUS" NUMBER DEFAULT 0, 
	"POINT" NUMBER, 
	"CDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BOM"."COUPON"."IDX" IS '인덱스 번호';
   COMMENT ON COLUMN "BOM"."COUPON"."NAME" IS '쿠폰명';
   COMMENT ON COLUMN "BOM"."COUPON"."MEMBER_ID" IS '쿠폰을 지급할 회원 아이디';
   COMMENT ON COLUMN "BOM"."COUPON"."STATUS" IS '0이면 미사용, 1이면 사용';
   COMMENT ON COLUMN "BOM"."COUPON"."POINT" IS '쿠폰 포인트';
   COMMENT ON COLUMN "BOM"."COUPON"."CDATE" IS '인덱스 걸어놓기';
   COMMENT ON TABLE "BOM"."COUPON"  IS '회원에게 지급될 포인트 쿠폰';
--------------------------------------------------------
--  DDL for Table DELIVERY_INFO
--------------------------------------------------------

  CREATE TABLE "BOM"."DELIVERY_INFO" 
   (	"IDX" NUMBER, 
	"MEMBER_ID" VARCHAR2(50 BYTE), 
	"RECEIVER_NAME" VARCHAR2(100 BYTE), 
	"RECEIVER_PHONE" VARCHAR2(20 BYTE), 
	"RECEIVER_ZIPCODE" VARCHAR2(20 BYTE), 
	"RECEIVER_ADDR_BASE" VARCHAR2(200 BYTE), 
	"RECEIVER_ADDR_DETAIL" VARCHAR2(200 BYTE), 
	"RECEIVER_ADDR_EXTRA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BOM"."DELIVERY_INFO"."IDX" IS '배송지 번호';
   COMMENT ON COLUMN "BOM"."DELIVERY_INFO"."MEMBER_ID" IS '주문자 아이디';
   COMMENT ON COLUMN "BOM"."DELIVERY_INFO"."RECEIVER_NAME" IS '수령인명';
   COMMENT ON COLUMN "BOM"."DELIVERY_INFO"."RECEIVER_PHONE" IS '수령인 전화번호';
   COMMENT ON COLUMN "BOM"."DELIVERY_INFO"."RECEIVER_ZIPCODE" IS '수령인 우편번호';
   COMMENT ON COLUMN "BOM"."DELIVERY_INFO"."RECEIVER_ADDR_BASE" IS '수령인 주소 (기본)';
   COMMENT ON COLUMN "BOM"."DELIVERY_INFO"."RECEIVER_ADDR_DETAIL" IS '수령인 주소 (상세)';
   COMMENT ON COLUMN "BOM"."DELIVERY_INFO"."RECEIVER_ADDR_EXTRA" IS '수령인 주소 (참고)';
   COMMENT ON TABLE "BOM"."DELIVERY_INFO"  IS '배송지 목록';
--------------------------------------------------------
--  DDL for Table ECOMMENT
--------------------------------------------------------

  CREATE TABLE "BOM"."ECOMMENT" 
   (	"IDX" NUMBER, 
	"MEMBER_ID" VARCHAR2(50 BYTE), 
	"IMAGE" VARCHAR2(500 BYTE), 
	"CONTENT" CLOB, 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"REPORT" NUMBER DEFAULT 0, 
	"EVENT_IDX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BOM"."ECOMMENT"."IDX" IS '이벤트 댓글 인덱스';
   COMMENT ON COLUMN "BOM"."ECOMMENT"."MEMBER_ID" IS '회원 아이디';
   COMMENT ON COLUMN "BOM"."ECOMMENT"."IMAGE" IS '댓글 이미지';
   COMMENT ON COLUMN "BOM"."ECOMMENT"."CONTENT" IS '댓글 내용';
   COMMENT ON COLUMN "BOM"."ECOMMENT"."REG_DATE" IS '댓글 등록일';
   COMMENT ON COLUMN "BOM"."ECOMMENT"."REPORT" IS '댓글 신고 수';
   COMMENT ON COLUMN "BOM"."ECOMMENT"."EVENT_IDX" IS '해당 이벤트 인덱스';
   COMMENT ON TABLE "BOM"."ECOMMENT"  IS '이벤트 게시판에 달릴 댓글 테이블';
--------------------------------------------------------
--  DDL for Table EVENT
--------------------------------------------------------

  CREATE TABLE "BOM"."EVENT" 
   (	"IDX" NUMBER, 
	"THUMB" VARCHAR2(500 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"IMAGE1" VARCHAR2(500 BYTE), 
	"IMAGE2" VARCHAR2(500 BYTE), 
	"CONTENT" CLOB, 
	"START_DATE" DATE, 
	"END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BOM"."EVENT"."IDX" IS '인덱스';
   COMMENT ON COLUMN "BOM"."EVENT"."THUMB" IS '썸네일 이미지';
   COMMENT ON COLUMN "BOM"."EVENT"."NAME" IS '이벤트명';
   COMMENT ON COLUMN "BOM"."EVENT"."IMAGE1" IS '상세페이지 이미지1';
   COMMENT ON COLUMN "BOM"."EVENT"."IMAGE2" IS '상세페이지 이미지2';
   COMMENT ON COLUMN "BOM"."EVENT"."CONTENT" IS '상세페이지 내용';
   COMMENT ON COLUMN "BOM"."EVENT"."START_DATE" IS '이벤트 시작일';
   COMMENT ON COLUMN "BOM"."EVENT"."END_DATE" IS '이벤트 종료일';
   COMMENT ON TABLE "BOM"."EVENT"  IS '이벤트';
--------------------------------------------------------
--  DDL for Table FAQ
--------------------------------------------------------

  CREATE TABLE "BOM"."FAQ" 
   (	"IDX" NUMBER, 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"QUESTION" VARCHAR2(1000 BYTE), 
	"ANSWER" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("ANSWER") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BOM"."FAQ"."IDX" IS '인덱스';
   COMMENT ON COLUMN "BOM"."FAQ"."CATEGORY" IS '질문 카테고리';
   COMMENT ON COLUMN "BOM"."FAQ"."QUESTION" IS '질문';
   COMMENT ON COLUMN "BOM"."FAQ"."ANSWER" IS '답안';
   COMMENT ON TABLE "BOM"."FAQ"  IS '자주 묻는 질문';
--------------------------------------------------------
--  DDL for Table FCB
--------------------------------------------------------

  CREATE TABLE "BOM"."FCB" 
   (	"FCLASS_IDX" NUMBER, 
	"BRANCH_IDX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FCLASS
--------------------------------------------------------

  CREATE TABLE "BOM"."FCLASS" 
   (	"IDX" NUMBER, 
	"CATEGORY" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"SUBHEADER" VARCHAR2(200 BYTE), 
	"PRICE" NUMBER, 
	"DISCOUNT_RATE" NUMBER, 
	"IMAGE1" VARCHAR2(500 BYTE), 
	"IMAGE2" VARCHAR2(500 BYTE), 
	"IMAGE3" VARCHAR2(500 BYTE), 
	"CONTENT" CLOB, 
	"COUNT" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BOM"."FCLASS"."IDX" IS '클래스 인덱스';
   COMMENT ON COLUMN "BOM"."FCLASS"."CATEGORY" IS '원데이, 플로리스트';
   COMMENT ON COLUMN "BOM"."FCLASS"."NAME" IS '클래스명';
   COMMENT ON COLUMN "BOM"."FCLASS"."SUBHEADER" IS '한줄 설명';
   COMMENT ON COLUMN "BOM"."FCLASS"."PRICE" IS '수강료';
   COMMENT ON COLUMN "BOM"."FCLASS"."DISCOUNT_RATE" IS '할인율';
   COMMENT ON COLUMN "BOM"."FCLASS"."IMAGE1" IS '클래스 이미지1';
   COMMENT ON COLUMN "BOM"."FCLASS"."IMAGE2" IS '클래스 이미지2';
   COMMENT ON COLUMN "BOM"."FCLASS"."IMAGE3" IS '클래스 이미지3';
   COMMENT ON COLUMN "BOM"."FCLASS"."CONTENT" IS '상세페이지 내용';
   COMMENT ON COLUMN "BOM"."FCLASS"."COUNT" IS '총 수업 횟수';
   COMMENT ON TABLE "BOM"."FCLASS"  IS '플라워 클래스';
--------------------------------------------------------
--  DDL for Table FLOWER
--------------------------------------------------------

  CREATE TABLE "BOM"."FLOWER" 
   (	"IDX" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"SUBHEADER" VARCHAR2(200 BYTE), 
	"PRICE" NUMBER, 
	"FSIZE" VARCHAR2(10 BYTE), 
	"DISCOUNT_RATE" NUMBER, 
	"IMAGE1" VARCHAR2(500 BYTE), 
	"IMAGE2" VARCHAR2(500 BYTE), 
	"IMAGE3" VARCHAR2(500 BYTE), 
	"CONTENT" CLOB, 
	"DEL_STATUS" VARCHAR2(10 BYTE), 
	"FREE_DELIVERY" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BOM"."FLOWER"."IDX" IS '꽃다발 인덱스';
   COMMENT ON COLUMN "BOM"."FLOWER"."NAME" IS '상품명';
   COMMENT ON COLUMN "BOM"."FLOWER"."SUBHEADER" IS '한줄 설명';
   COMMENT ON COLUMN "BOM"."FLOWER"."PRICE" IS '가격';
   COMMENT ON COLUMN "BOM"."FLOWER"."FSIZE" IS '사이즈';
   COMMENT ON COLUMN "BOM"."FLOWER"."DISCOUNT_RATE" IS '할인율';
   COMMENT ON COLUMN "BOM"."FLOWER"."IMAGE1" IS '상품 이미지1';
   COMMENT ON COLUMN "BOM"."FLOWER"."IMAGE2" IS '상품 이미지2';
   COMMENT ON COLUMN "BOM"."FLOWER"."IMAGE3" IS '상품 이미지3';
   COMMENT ON COLUMN "BOM"."FLOWER"."CONTENT" IS '상세페이지 내용';
   COMMENT ON COLUMN "BOM"."FLOWER"."DEL_STATUS" IS '삭제되면 DEL, 아니면 null';
   COMMENT ON COLUMN "BOM"."FLOWER"."FREE_DELIVERY" IS '0이면 무료배송 아님, 1이면 무료배송';
   COMMENT ON TABLE "BOM"."FLOWER"  IS '꽃다발';
--------------------------------------------------------
--  DDL for Table MAIN
--------------------------------------------------------

  CREATE TABLE "BOM"."MAIN" 
   (	"FCLASS_IDX_BIG" NUMBER, 
	"FCLASS_IDX_SMALL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "BOM"."MAIN"  IS '메인 관리화면';
--------------------------------------------------------
--  DDL for Table MAIN_IMAGE
--------------------------------------------------------

  CREATE TABLE "BOM"."MAIN_IMAGE" 
   (	"IDX" NUMBER, 
	"PATH" VARCHAR2(500 BYTE), 
	"LINK" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "BOM"."MEMBER" 
   (	"ID" VARCHAR2(50 BYTE), 
	"PW" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"BIRTH" DATE, 
	"GENDER" VARCHAR2(10 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"GRADE" VARCHAR2(20 BYTE) DEFAULT '데이지', 
	"POINT" NUMBER DEFAULT 1000, 
	"QUIT_STATUS" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BOM"."MEMBER"."ID" IS '아이디(이메일주소)';
   COMMENT ON COLUMN "BOM"."MEMBER"."PW" IS '비밀번호';
   COMMENT ON COLUMN "BOM"."MEMBER"."NAME" IS '이름';
   COMMENT ON COLUMN "BOM"."MEMBER"."BIRTH" IS '생년월일';
   COMMENT ON COLUMN "BOM"."MEMBER"."GENDER" IS '성별';
   COMMENT ON COLUMN "BOM"."MEMBER"."PHONE" IS '핸드폰 번호';
   COMMENT ON COLUMN "BOM"."MEMBER"."GRADE" IS '회원 등급';
   COMMENT ON COLUMN "BOM"."MEMBER"."POINT" IS '포인트';
   COMMENT ON COLUMN "BOM"."MEMBER"."QUIT_STATUS" IS '0이면 가입, 1이면 탈퇴';
   COMMENT ON TABLE "BOM"."MEMBER"  IS '회원';
--------------------------------------------------------
--  DDL for Table MYQ
--------------------------------------------------------

  CREATE TABLE "BOM"."MYQ" 
   (	"IDX" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"CONTENT" CLOB, 
	"IMAGE" VARCHAR2(500 BYTE), 
	"MEMBER_ID" VARCHAR2(50 BYTE), 
	"EMAIL_SEND" NUMBER DEFAULT 0, 
	"ANSWER" CLOB, 
	"QUESTION_DATE" DATE, 
	"ANSWER_DATE" DATE, 
	"ANSWER_TITLE" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ANSWER") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BOM"."MYQ"."IDX" IS '일대일문의 인덱스';
   COMMENT ON COLUMN "BOM"."MYQ"."NAME" IS '문의글 제목';
   COMMENT ON COLUMN "BOM"."MYQ"."CONTENT" IS '문의글 내용';
   COMMENT ON COLUMN "BOM"."MYQ"."IMAGE" IS '첨부 이미지';
   COMMENT ON COLUMN "BOM"."MYQ"."MEMBER_ID" IS '질문한 회원 아이디';
   COMMENT ON COLUMN "BOM"."MYQ"."EMAIL_SEND" IS '0이 안보냄, 1이 보냄';
   COMMENT ON COLUMN "BOM"."MYQ"."ANSWER" IS 'null이면 미답변, not null이면 답변완료';
   COMMENT ON TABLE "BOM"."MYQ"  IS '나의 문의 (일대일 문의)';
--------------------------------------------------------
--  DDL for Table OCLASS
--------------------------------------------------------

  CREATE TABLE "BOM"."OCLASS" 
   (	"IDX" NUMBER, 
	"MEMBER_ID" VARCHAR2(50 BYTE), 
	"REG_COUNT" NUMBER, 
	"PAY_TYPE" VARCHAR2(50 BYTE), 
	"PAY_TOTAL" NUMBER, 
	"PAY_DATE" DATE, 
	"DISCOUNT_GRADE" NUMBER, 
	"DISCOUNT_POINT" NUMBER, 
	"FCLASS_NAME" VARCHAR2(100 BYTE), 
	"BRANCH_NAME" VARCHAR2(50 BYTE), 
	"BRANCH_ADDR" VARCHAR2(500 BYTE), 
	"FCLASS_IMAGE" VARCHAR2(500 BYTE), 
	"SCHEDULE_DATE" DATE, 
	"SCHEDULE_START_TIME" VARCHAR2(20 BYTE), 
	"SCHEDULE_END_TIME" VARCHAR2(20 BYTE), 
	"FCLASS_COUNT" NUMBER DEFAULT 1, 
	"STATUS" VARCHAR2(20 BYTE), 
	"REVIEW_CHECK" NUMBER DEFAULT 0, 
	"DISCOUNT_TOTAL_PRICE" NUMBER, 
	"FCLASS_IDX" NUMBER, 
	"SCHEDULE_IDX" NUMBER, 
	"ORDER_DATE" DATE DEFAULT SYSDATE, 
	"REVIEW_IDX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BOM"."OCLASS"."IDX" IS '클래스 주문 번호';
   COMMENT ON COLUMN "BOM"."OCLASS"."MEMBER_ID" IS '클래스 주문자 아이디';
   COMMENT ON COLUMN "BOM"."OCLASS"."REG_COUNT" IS '수강 신청 인원';
   COMMENT ON COLUMN "BOM"."OCLASS"."PAY_TYPE" IS '신용카드, 현금, 카카오페이';
   COMMENT ON COLUMN "BOM"."OCLASS"."PAY_TOTAL" IS '총 결제금액';
   COMMENT ON COLUMN "BOM"."OCLASS"."PAY_DATE" IS '결제 일시';
   COMMENT ON COLUMN "BOM"."OCLASS"."DISCOUNT_GRADE" IS '등급 할인';
   COMMENT ON COLUMN "BOM"."OCLASS"."DISCOUNT_POINT" IS '포인트 할인';
   COMMENT ON COLUMN "BOM"."OCLASS"."FCLASS_NAME" IS '클래스명';
   COMMENT ON COLUMN "BOM"."OCLASS"."BRANCH_NAME" IS '지점명';
   COMMENT ON COLUMN "BOM"."OCLASS"."BRANCH_ADDR" IS '지점주소';
   COMMENT ON COLUMN "BOM"."OCLASS"."FCLASS_IMAGE" IS '클래스 상품 사진';
   COMMENT ON COLUMN "BOM"."OCLASS"."SCHEDULE_DATE" IS '클래스 수강월일';
   COMMENT ON COLUMN "BOM"."OCLASS"."SCHEDULE_START_TIME" IS '수업 시작 시간';
   COMMENT ON COLUMN "BOM"."OCLASS"."SCHEDULE_END_TIME" IS '수업 끝나는 시간';
   COMMENT ON COLUMN "BOM"."OCLASS"."FCLASS_COUNT" IS '총 수업 횟수';
   COMMENT ON COLUMN "BOM"."OCLASS"."STATUS" IS '입금대기, 수강예정, 수강중, 수강완료';
   COMMENT ON COLUMN "BOM"."OCLASS"."REVIEW_CHECK" IS '1이면 리뷰 씀';
   COMMENT ON TABLE "BOM"."OCLASS"  IS '플라워클래스 결제';
--------------------------------------------------------
--  DDL for Table OITEM
--------------------------------------------------------

  CREATE TABLE "BOM"."OITEM" 
   (	"IDX" NUMBER, 
	"ORDERS_IDX" NUMBER, 
	"LETTER_CONTENT" VARCHAR2(500 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER, 
	"OPTIONS" VARCHAR2(3000 BYTE), 
	"IMAGE" VARCHAR2(500 BYTE), 
	"REQUEST_DATE" DATE, 
	"DELIVERY_START_DATE" DATE, 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"REVIEW_CHECK" NUMBER DEFAULT 0, 
	"QUANTITY" NUMBER, 
	"FSIZE" VARCHAR2(10 BYTE), 
	"REVIEW_IDX" NUMBER, 
	"ITEM_IDX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BOM"."OITEM"."IDX" IS '주문상품 번호';
   COMMENT ON COLUMN "BOM"."OITEM"."ORDERS_IDX" IS '주문 번호';
   COMMENT ON COLUMN "BOM"."OITEM"."LETTER_CONTENT" IS '편지 내용';
   COMMENT ON COLUMN "BOM"."OITEM"."NAME" IS '상품명';
   COMMENT ON COLUMN "BOM"."OITEM"."PRICE" IS '상품 가격';
   COMMENT ON COLUMN "BOM"."OITEM"."OPTIONS" IS '콤마로 구분';
   COMMENT ON COLUMN "BOM"."OITEM"."IMAGE" IS '상품 테이블에서 image1에 해당하는 상품사진';
   COMMENT ON COLUMN "BOM"."OITEM"."REQUEST_DATE" IS '수령 요청일';
   COMMENT ON COLUMN "BOM"."OITEM"."DELIVERY_START_DATE" IS '배송 시작일';
   COMMENT ON COLUMN "BOM"."OITEM"."CATEGORY" IS '정기구독, 꽃다발, 소품샵';
   COMMENT ON COLUMN "BOM"."OITEM"."REVIEW_CHECK" IS '1이면 리뷰 씀';
   COMMENT ON COLUMN "BOM"."OITEM"."QUANTITY" IS '수량';
   COMMENT ON TABLE "BOM"."OITEM"  IS '주문 상세';
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "BOM"."ORDERS" 
   (	"IDX" NUMBER, 
	"MEMBER_ID" VARCHAR2(50 BYTE), 
	"ODATE" DATE DEFAULT SYSDATE, 
	"RECEIVER_NAME" VARCHAR2(100 BYTE), 
	"RECEIVER_PHONE" VARCHAR2(20 BYTE), 
	"RECEIVER_ZIPCODE" VARCHAR2(20 BYTE), 
	"RECEIVER_ADDR_BASE" VARCHAR2(200 BYTE), 
	"RECEIVER_ADDR_DETAIL" VARCHAR2(200 BYTE), 
	"RECEIVER_ADDR_EXTRA" VARCHAR2(200 BYTE), 
	"SENDER_NAME" VARCHAR2(100 BYTE), 
	"PAY_TYPE" VARCHAR2(50 BYTE), 
	"PAY_TOTAL" NUMBER, 
	"PAY_DELIVERY" NUMBER, 
	"PAY_DATE" DATE, 
	"DISCOUNT_GRADE" NUMBER, 
	"DISCOUNT_POINT" NUMBER, 
	"STATUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BOM"."ORDERS"."IDX" IS '주문 번호';
   COMMENT ON COLUMN "BOM"."ORDERS"."MEMBER_ID" IS '주문자 아이디';
   COMMENT ON COLUMN "BOM"."ORDERS"."ODATE" IS '주문일';
   COMMENT ON COLUMN "BOM"."ORDERS"."RECEIVER_NAME" IS '수령인명';
   COMMENT ON COLUMN "BOM"."ORDERS"."RECEIVER_PHONE" IS '수령인 연락처';
   COMMENT ON COLUMN "BOM"."ORDERS"."RECEIVER_ZIPCODE" IS '수령인 우편번호';
   COMMENT ON COLUMN "BOM"."ORDERS"."RECEIVER_ADDR_BASE" IS '수령인 주소 (기본)';
   COMMENT ON COLUMN "BOM"."ORDERS"."RECEIVER_ADDR_DETAIL" IS '수령인 주소 (상세)';
   COMMENT ON COLUMN "BOM"."ORDERS"."RECEIVER_ADDR_EXTRA" IS '수령인 주소 (참고)';
   COMMENT ON COLUMN "BOM"."ORDERS"."SENDER_NAME" IS '보내는 사람 이름';
   COMMENT ON COLUMN "BOM"."ORDERS"."PAY_TYPE" IS '결제수단';
   COMMENT ON COLUMN "BOM"."ORDERS"."PAY_TOTAL" IS '총 결제금액';
   COMMENT ON COLUMN "BOM"."ORDERS"."PAY_DELIVERY" IS '배송비';
   COMMENT ON COLUMN "BOM"."ORDERS"."PAY_DATE" IS '결제일시';
   COMMENT ON COLUMN "BOM"."ORDERS"."DISCOUNT_GRADE" IS '등급 할인';
   COMMENT ON COLUMN "BOM"."ORDERS"."DISCOUNT_POINT" IS '포인트 할인';
   COMMENT ON COLUMN "BOM"."ORDERS"."STATUS" IS '주문상태';
   COMMENT ON TABLE "BOM"."ORDERS"  IS '주문과 결제에 대한 정보가 저장 (카트 정보를 오더테이블에 저장)';
--------------------------------------------------------
--  DDL for Table OSUBS
--------------------------------------------------------

  CREATE TABLE "BOM"."OSUBS" 
   (	"IDX" NUMBER, 
	"OITEM_IDX" NUMBER, 
	"MONTH" NUMBER, 
	"DELIVERY_DATE" DATE, 
	"DELIVERY_STATUS" VARCHAR2(50 BYTE) DEFAULT '배송전'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BOM"."OSUBS"."IDX" IS '인덱스';
   COMMENT ON COLUMN "BOM"."OSUBS"."OITEM_IDX" IS '주문상세 인덱스';
   COMMENT ON COLUMN "BOM"."OSUBS"."MONTH" IS '정기구독 기간';
   COMMENT ON COLUMN "BOM"."OSUBS"."DELIVERY_DATE" IS '정기구독용 배송일';
   COMMENT ON COLUMN "BOM"."OSUBS"."DELIVERY_STATUS" IS '배송전, 배송후';
   COMMENT ON TABLE "BOM"."OSUBS"  IS '정기 구독의 결제 완료 테이블';
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "BOM"."PRODUCT" 
   (	"IDX" NUMBER, 
	"CATEGORY" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"SUBHEADER" VARCHAR2(200 BYTE), 
	"PRICE" NUMBER, 
	"DISCOUNT_RATE" NUMBER, 
	"IMAGE1" VARCHAR2(500 BYTE), 
	"IMAGE2" VARCHAR2(500 BYTE), 
	"IMAGE3" VARCHAR2(500 BYTE), 
	"CONTENT" CLOB, 
	"DEL_STATUS" VARCHAR2(10 BYTE), 
	"SOLDOUT_STATUS" VARCHAR2(20 BYTE), 
	"FSIZE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BOM"."PRODUCT"."IDX" IS '소품샵 인덱스';
   COMMENT ON COLUMN "BOM"."PRODUCT"."CATEGORY" IS '꽃병, 툴';
   COMMENT ON COLUMN "BOM"."PRODUCT"."NAME" IS '상품명';
   COMMENT ON COLUMN "BOM"."PRODUCT"."SUBHEADER" IS '한줄 설명';
   COMMENT ON COLUMN "BOM"."PRODUCT"."PRICE" IS '가격';
   COMMENT ON COLUMN "BOM"."PRODUCT"."DISCOUNT_RATE" IS '할인율';
   COMMENT ON COLUMN "BOM"."PRODUCT"."IMAGE1" IS '상품 이미지1';
   COMMENT ON COLUMN "BOM"."PRODUCT"."IMAGE2" IS '상품 이미지2';
   COMMENT ON COLUMN "BOM"."PRODUCT"."IMAGE3" IS '상품 이미지3';
   COMMENT ON COLUMN "BOM"."PRODUCT"."CONTENT" IS '상세페이지 내용';
   COMMENT ON COLUMN "BOM"."PRODUCT"."DEL_STATUS" IS '삭제되면 DEL, 아니면 null';
   COMMENT ON COLUMN "BOM"."PRODUCT"."SOLDOUT_STATUS" IS '재고 없으면 SOLD OUT, 아니면 null';
   COMMENT ON COLUMN "BOM"."PRODUCT"."FSIZE" IS '화병인 경우만';
   COMMENT ON TABLE "BOM"."PRODUCT"  IS '소품샵';
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "BOM"."REVIEW" 
   (	"IDX" NUMBER, 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"SUBS_IDX" NUMBER, 
	"FLOWER_IDX" NUMBER, 
	"FCLASS_IDX" NUMBER, 
	"PRODUCT_IDX" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"MEMBER_ID" VARCHAR2(50 BYTE), 
	"IMAGE" VARCHAR2(500 BYTE), 
	"CONTENT" CLOB, 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"STAR" NUMBER, 
	"LIKE_COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BOM"."REVIEW"."IDX" IS '리뷰 인덱스';
   COMMENT ON COLUMN "BOM"."REVIEW"."CATEGORY" IS '꽃다발, 정기구독, 소품샵, 플라워클래스';
   COMMENT ON COLUMN "BOM"."REVIEW"."SUBS_IDX" IS '정기구독 인덱스';
   COMMENT ON COLUMN "BOM"."REVIEW"."FLOWER_IDX" IS '꽃다발 인덱스';
   COMMENT ON COLUMN "BOM"."REVIEW"."FCLASS_IDX" IS '클래스 인덱스';
   COMMENT ON COLUMN "BOM"."REVIEW"."PRODUCT_IDX" IS '소품샵 인덱스';
   COMMENT ON COLUMN "BOM"."REVIEW"."NAME" IS '리뷰 제목';
   COMMENT ON COLUMN "BOM"."REVIEW"."MEMBER_ID" IS '작성자 아이디';
   COMMENT ON COLUMN "BOM"."REVIEW"."IMAGE" IS '리뷰 이미지';
   COMMENT ON COLUMN "BOM"."REVIEW"."CONTENT" IS '리뷰 내용';
   COMMENT ON COLUMN "BOM"."REVIEW"."REG_DATE" IS '리뷰 등록일';
   COMMENT ON COLUMN "BOM"."REVIEW"."STAR" IS '1, 2, 3, 4, 5 중 택1';
   COMMENT ON COLUMN "BOM"."REVIEW"."LIKE_COUNT" IS '좋아요 숫자';
   COMMENT ON TABLE "BOM"."REVIEW"  IS '리뷰게시판';
--------------------------------------------------------
--  DDL for Table REVIEW_LIKE
--------------------------------------------------------

  CREATE TABLE "BOM"."REVIEW_LIKE" 
   (	"IDX" NUMBER, 
	"REVIEW_IDX" NUMBER, 
	"MEMBER_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SCHEDULE
--------------------------------------------------------

  CREATE TABLE "BOM"."SCHEDULE" 
   (	"IDX" NUMBER, 
	"BRANCH_IDX" NUMBER, 
	"FCLASS_IDX" NUMBER, 
	"SDATE" DATE, 
	"SMONTH" NUMBER, 
	"SDAY" NUMBER, 
	"START_TIME" VARCHAR2(20 BYTE), 
	"END_TIME" VARCHAR2(20 BYTE), 
	"TOTAL_COUNT" NUMBER, 
	"REG_COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BOM"."SCHEDULE"."IDX" IS '일정 인덱스';
   COMMENT ON COLUMN "BOM"."SCHEDULE"."BRANCH_IDX" IS '지점 인덱스';
   COMMENT ON COLUMN "BOM"."SCHEDULE"."FCLASS_IDX" IS '클래스 인덱스';
   COMMENT ON COLUMN "BOM"."SCHEDULE"."SDATE" IS '클래스 수강월일';
   COMMENT ON COLUMN "BOM"."SCHEDULE"."SMONTH" IS '수강-월';
   COMMENT ON COLUMN "BOM"."SCHEDULE"."SDAY" IS '수강-일';
   COMMENT ON COLUMN "BOM"."SCHEDULE"."START_TIME" IS '24시간제, minute 안 씀';
   COMMENT ON COLUMN "BOM"."SCHEDULE"."END_TIME" IS '24시간제, minute 안 씀';
   COMMENT ON COLUMN "BOM"."SCHEDULE"."TOTAL_COUNT" IS '수강 정원';
   COMMENT ON COLUMN "BOM"."SCHEDULE"."REG_COUNT" IS '수강 등록한 회원 수';
   COMMENT ON TABLE "BOM"."SCHEDULE"  IS '일정';
--------------------------------------------------------
--  DDL for Table SUBS
--------------------------------------------------------

  CREATE TABLE "BOM"."SUBS" 
   (	"IDX" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"SUBHEADER" VARCHAR2(200 BYTE), 
	"SUMMARY" VARCHAR2(1000 BYTE), 
	"PRICE" NUMBER, 
	"IMAGE1" VARCHAR2(500 BYTE), 
	"IMAGE2" VARCHAR2(500 BYTE), 
	"IMAGE3" VARCHAR2(500 BYTE), 
	"CONTENT" CLOB, 
	"FSIZE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BOM"."SUBS"."IDX" IS '인덱스 번호';
   COMMENT ON COLUMN "BOM"."SUBS"."NAME" IS '상품명';
   COMMENT ON COLUMN "BOM"."SUBS"."SUBHEADER" IS '한줄 설명';
   COMMENT ON COLUMN "BOM"."SUBS"."SUMMARY" IS '상품 개요';
   COMMENT ON COLUMN "BOM"."SUBS"."PRICE" IS '상품 가격';
   COMMENT ON COLUMN "BOM"."SUBS"."IMAGE1" IS '상품 이미지1';
   COMMENT ON COLUMN "BOM"."SUBS"."IMAGE2" IS '상품 이미지2';
   COMMENT ON COLUMN "BOM"."SUBS"."IMAGE3" IS '상품 이미지3';
   COMMENT ON COLUMN "BOM"."SUBS"."CONTENT" IS '상세페이지 내용';
   COMMENT ON TABLE "BOM"."SUBS"  IS '꽃 정기구독';

